CUDA_VISIBLE_DEVICES=0 accelerate launch mlm.py \
--train_file /work/transfer2/pretrain/tweet_hash_clean_group_111_100.txt \
--model_name_or_path vinai/bertweet-base \
--tokenizer_name vinai/bertweet-base \
--output_dir /work/transfer2/pretrain/hashtag/hash_group_111_100/ \
--max_seq_length 128 \
--preprocessing_num_workers 10 \
--per_device_train_batch_size 128 \
--gradient_accumulation_steps 8 \
--num_train_epoch 10 \
--learning_rate 1e-4 \
--weight_decay 1e-2 \
--num_warmup_steps 5000